import { IsString, IsUUID, MinLength, MaxLength } from 'class-validator';

/* Session ids are generated by the browser and only ever group one visitor's
   own demo rows, so they are treated as an opaque string with a length bound
   rather than a credential. */
export class EnrollDto {
  @IsUUID()                                  courseId: string;
  @IsString() @MinLength(8) @MaxLength(64)   sessionId: string;
}

export class ProgressDto {
  @IsUUID()                                  topicId: string;
  @IsString() @MinLength(8) @MaxLength(64)   sessionId: string;
}
